// src/frontend/src/components/TaskItem.jsx
import { useState } from 'react';
import PropTypes from 'prop-types';
import { toast } from 'react-toastify';

function TaskItem({ item, token, setItems }) {
  const [itemState, setItemState] = useState(item);

  const toggle = async (e) => {
    const newCompletionStatus = e.target.checked;

    const resp = await fetch(`/api/Task/Toggle?taskId=${item.id}`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ isCompleted: newCompletionStatus }),
    });

    if (resp.ok) {
      setItemState((prevState) => ({
        ...prevState,
        isCompleted: newCompletionStatus,
      }));
      toast.success('Task status updated!', {
        autoClose: 1200,
      });
    } else {
      console.error('Failed to toggle task');
      setItemState((prevState) => ({
        ...prevState,
        isCompleted: !prevState.isCompleted,
      }));
      toast.error('Failed to update task status!');
    }
  };

  const remove = async () => {
    const resp = await fetch(`/api/Task/Remove?taskId=${item.id}`, {
      method: 'DELETE',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${token}`,
      },
    });

    if (resp.ok) {
      console.log('Item removed');
      setItems((prevItems) => prevItems.filter((task) => task.id !== item.id));
      toast.success('Task removed!', {
        autoClose: 1200,
      });
    } else {
      console.error('Failed to remove task');
      toast.error('Failed to remove task!');
    }
  };

  return (
    <div
      className={`flex items-center justify-between p-4 rounded-lg shadow-md mb-2 cursor-pointer ${
        itemState.isCompleted
          ? 'bg-gray-100 line-through text-gray-500'
          : 'bg-white'
      }`}
    >
      <input
        type="checkbox"
        className="chk-toggle rounded-full border-gray-300"
        checked={itemState.isCompleted}
        onChange={toggle}
      />
      <span
        className={`ml-3 flex-1 text-gray-700 ${
          itemState.isCompleted ? 'text-gray-400' : ''
        }`}
      >
        {itemState.text}
      </span>
      <a
        title="Remove item"
        className="text-red-600 cursor-pointer hover:text-red-700"
        onClick={remove}
      >
        X
      </a>
    </div>
  );
}

TaskItem.propTypes = {
  item: PropTypes.shape({
    id: PropTypes.string.isRequired,
    text: PropTypes.string.isRequired,
    isCompleted: PropTypes.bool.isRequired,
  }).isRequired,
  token: PropTypes.string.isRequired,
  setItems: PropTypes.func.isRequired,
};

export default TaskItem;

// src/client/src/components/TaskItem.vue
<template>
  <div class="flex items-center justify-between">
    <input
      type="checkbox"
      class="chk-toggle rounded-full border-gray-300"
      :checked="item.isCompleted"
      @click.stop="toggle(item.id)"
    />
    <span
      class="ml-3 text-gray-700 flex-1"
      :class="{ 'line-through text-gray-400': item.isCompleted }"
      v-html="item.text"
    ></span>
    <a
      title="Remove item"
      class="text-red-600 cursor-pointer"
      @click.stop="remove(item.id)"
    >
      X
    </a>
  </div>
</template>

<script setup>
import { defineProps, defineEmits } from 'vue';
import { userStore } from '../store/userStore';
import { apiCall } from '../utils/apiCall';

const props = defineProps({
  item: Object,
});

const emit = defineEmits(['itemUpdated']);

async function toggle(itemId) {
  try {
    const resp = await fetch(`/api/Task/Toggle?taskId=${itemId}`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${userStore.token}`,
      },
    });

    if (!resp.ok) throw new Error('Toggle failed');
    emit('itemUpdated');
  } catch (error) {
    console.error('Toggle error:', error);
  }
}

async function remove(itemId) {
  try {
    const result = await apiCall(
      `/api/Task/Remove?taskId=${itemId}`,
      'DELETE',
      null,
      userStore.token
    );
    if (result) {
      emit('itemUpdated');
    }
  } catch (error) {
    console.error('Remove error:', error);
  }
}
</script>
