// src/client/src/components/TaskList.vue
<template>
  <div class="text-center py-8">
    <span class="text-sm text-gray-600 mb-4 block">
      Items ({{ completeCount }} tasks complete / {{ incompleteCount }} tasks
      incomplete):
    </span>
    <div class="item-list space-y-3">
      <task-item
        v-for="item in items"
        :key="item.id"
        :item="item"
        @item-updated="updateList"
        class="flex items-center justify-between bg-white p-4 rounded-lg shadow-md hover:bg-gray-50"
      />
    </div>
    <hr class="my-6 border-t border-gray-300" />
    <div class="task-add space-x-4">
      <span class="text-sm text-gray-700">Add new item to list:</span>
      <input
        ref="taskInput"
        type="text"
        v-model="newItemText"
        class="px-4 py-2 border border-gray-300 rounded-md shadow-sm mt-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
        @keyup.enter="addItem"
      />
      <button
        type="button"
        @click="addItem"
        class="bg-blue-600 text-white py-2 px-6 rounded-md mt-2 cursor-pointer hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 transition duration-200 easy-in"
      >
        Add
      </button>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, computed, nextTick } from 'vue';
import { userStore } from '../store/userStore';
import { apiCall } from '../utils/apiCall';
import TaskItem from './TaskItem.vue';

const items = ref([]);
const newItemText = ref('');
const store = userStore;

async function addItem() {
  if (newItemText.value.trim() === '') return;
  const task = await apiCall(
    '/api/Task/Add',
    'POST',
    { text: newItemText.value, owner: store.currentUser, isCompleted: false },
    store.token
  );
  if (task) {
    newItemText.value = '';
    updateList();
  }
}

async function updateList() {
  const tasks = await apiCall(
    `/api/Task/List?userName=${encodeURIComponent(store.currentUser)}`,
    'GET',
    null,
    store.token
  );
  if (tasks) items.value = tasks;
}

const completeCount = computed(
  () => items.value.filter((q) => q.isCompleted).length
);
const incompleteCount = computed(
  () => items.value.filter((q) => !q.isCompleted).length
);

onMounted(() => {
  updateList();
  nextTick(() => document.querySelector('input[ref=taskInput]')?.focus());
});
</script>

// src/frontend/src/components/TaskList.jsx
import { useState, useEffect } from 'react';
import PropTypes from 'prop-types';
import TaskItem from './TaskItem';
import { apiCall } from '../utils/api';
import { toast } from 'react-toastify';

function TaskList({ token, currentUser }) {
  const [items, setItems] = useState([]);
  const [newItemText, setNewItemText] = useState('');

  useEffect(() => {
    async function fetchTasks() {
      const tasks = await apiCall(
        `/api/Task/List?userName=${encodeURIComponent(currentUser)}`,
        'GET',
        null,
        token
      );
      setItems(tasks || []);
    }
    fetchTasks();
  }, [currentUser, token]);

  const addItem = async () => {
    if (newItemText.length < 1) return;
    const task = await apiCall(
      '/api/Task/Add',
      'POST',
      { text: newItemText, owner: currentUser, isCompleted: false },
      token
    );
    if (task) {
      setNewItemText('');
      setItems((prevItems) => [...prevItems, task]);
      toast.success('Task added!', {
        closeButton: true,
        customProgressBar: false,
        autoClose: 1200,
      });
    }
  };

  const completeCount = items.filter((item) => item.isCompleted).length;
  const incompleteCount = items.filter((item) => !item.isCompleted).length;

  return (
    <div className="max-w-2xl mx-auto p-4">
      <span className="block mb-4 text-lg font-semibold text-gray-700 text-center">
        Items ({completeCount} tasks complete/{incompleteCount} tasks
        incomplete):
      </span>
      <div className="space-y-4">
        {items.map((item) => (
          <TaskItem
            key={item.id}
            item={item}
            token={token}
            setItems={setItems}
          />
        ))}
      </div>
      <hr className="my-6 border-t border-gray-300" />
      <div className="task-add flex items-center justify-center space-x-4">
        <span className="text-sm text-gray-600">Add new item to list:</span>
        <input
          type="text"
          value={newItemText}
          onChange={(e) => setNewItemText(e.target.value)}
          onKeyUp={(e) => e.key === 'Enter' && addItem()}
          className="px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
        <button
          onClick={addItem}
          className="bg-blue-600 text-white py-2 px-6 rounded-md cursor-pointer hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          Add
        </button>
      </div>
    </div>
  );
}
TaskList.propTypes = {
  token: PropTypes.string.isRequired,
  currentUser: PropTypes.string.isRequired,
};

export default TaskList;
